version: 2

models:
    - name: dim_vendors
      columns:
          - name: id
            tests:
                - not_null
                - unique
    - name: fact_trips
      columns:      
          - name: id
            tests:
                - not_null
                - unique
    - name: dim_locations
      columns:      
          - name: id
            tests:
                - not_null
                - unique
